### ISSUE TITLE
Push out 0.08 ~ fixes in Apr 2016 not released (causing install test failures)

### ISSUE THREAD

**Issue by rivy** [karupanerura/TOML-Parser#10]
Commits on Apr 4 (and specifically 475da696ace5bcd70a2d31fa134df89b1d45bd20) have not been pushed to CPAN. This is causing install test failures.

commit @ 475da696ace5bcd70a2d31fa134df89b1d45bd20 tests / installs cleanly.

**Comment by karupanerura** [comment]
Sorry for late. I'll release it soon.

**Comment by karupanerura** [comment]
I released it as 0.08. Please try it.

**Comment by rivy** [comment]
Looks good here ... thanks!
