### ISSUE TITLE
Tests fail with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [karupanerura/TOML-Parser#7]
Tests fail if perl was compiled with -Duselongdouble:
```
#   Failed test 'float.toml: strict: 0'
#   at t/001_parser/float.t line 30.
#     Structures begin differing at:
#          $got->{key8} = '9224617.44599122831'
#     $expected->{key8} = '9224617.44599123'

#   Failed test 'float.toml: strict: 1'
#   at t/001_parser/float.t line 30.
#     Structures begin differing at:
#          $got->{key8} = '9224617.44599122831'
#     $expected->{key8} = '9224617.44599123'
# Looks like you failed 2 tests of 2.
t/001_parser/float.t ................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
```
See also http://matrix.cpantesters.org/?dist=TOML-Parser;os=linux;reports=1 for an overview of linux test reports --- it fails for `archname=~/ld/` (ld = longdouble).

**Comment by karupanerura** [comment]
Thank you for reporting! I'll fix test in near future.

**Comment by eserte** [comment]
Same problem with TOML-Parser-0.07

**Comment by andk** [comment]
A convenient module to apply an epsilon for floating point comparisons is Test::Number::Delta.

**Comment by karupanerura** [comment]
oops. I forgot it. sorry.
I'll fix it at tomorrow.
